name: Lint Swift Files
on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/lint.yml"
      - ".swiftlint.yml"
      - "**/*.swift"
  pull_request:
    paths:
      - ".github/workflows/lint.yml"
      - ".swiftlint.yml"
      - "**/*.swift"

permissions:
  contents: read

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  swiftlint:
    if: '!github.event.pull_request.merged'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Run SwiftLint
        uses: norio-nomura/action-swiftlint@9f4dcd7fd46b4e75d7935cf2f4df406d5cae3684 # 3.2.1
        with:
          args: --strict
